#-------------------------------
# Site Settings

title: RyChan
tab__title: RyChan - Sà Và Ná Design Concept.
meta__title: RyChan - Sà Và Ná Design Concept.
logo: # You can add own logo. For example '/images/logo.png'
description: RyChan - Sà Và Ná Design Concept.

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blogs'
      url: '/blog/'
    - title: 'Categories'
      url: '/categories/'
    - title: 'About'
      url: '/about/'
    # - title: 'Contact'
    #  url: '/contact'
    # - title: 'Pages'
    #   submenu:
    #   - url: '/about'
    #     title: 'About'
    #   - url: '/elements'
    #     title: 'Elements'

# Call to action button
cta__button__text: Inbox me
cta__button_url: 'https://m.me/Saigonvanang'

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: 'https://i.imgur.com/MkaBAt0.jpeg'


#-------------------------------
# Author Settings

author:
  name: Ry Nguyễn
  title: Hi, I’m RY / NHUNG NGUYEN
  # bio: Art Director & Graphic Designer based in Ho Chi Minh City
  bio: "
    An illustrator based in Saigon, Vietnam. Here you can see some of my latest WORK. Feel free to snoop around on my SOCIAL MEDIA or inquiries or a how you doing CONTACT ME.
I will be happy to hear from you. 🧑🏻‍🎨
    "
  image: 'https://i.imgur.com/MkaBAt0.jpeg'
  avatar: 'https://i.imgur.com/MkaBAt0.jpeg'
  button__text: See my work


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Latest <span class="text-span">Work</span> # Add a 'text-span' class to highlight text.
  projects__description: "
    An illustrator based in Saigon, Vietnam. Here you can see some of my latest WORK.
    "


#-------------------------------
# Testimonials Section

testimonial__title: My Happy <span class="text-span">Teammates & Clients</span> # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: "Chang Duong"
    image: "https://i.imgur.com/MkaBAt0.jpeg"
    designation : "Graphic Designer @ Sky Corp."
    content : "Ry Nguyen is my best partner ever. Ry Nguyen is my best partner ever."

  - name: "Hoang Dang"
    image: "https://i.imgur.com/MkaBAt0.jpeg"
    designation : "Product Manager @ OMC"
    content : "I am very proud of Ry, cause of her creative and contribution for team!"

  - name: "Circus Squad"
    image: "https://i.imgur.com/MkaBAt0.jpeg"
    designation : "Loyalty Product @ OMC"
    content : "She is our big-sister at company. She is our big-sister at company."

  # - name: "Julie Arnold"
  #   image: "/images/client-4.jpg"
  #   designation : "Full stack developer"
  #   content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


#-------------------------------
# Blog Section

blog__settings:
  blog__title: Recent <span class="text-span">Blog</span> Posts # Add a 'text-span' class to highlight text.
  blog__description: An illustrator based in Saigon, Vietnam. Here you can see some of my latest WORK.


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: hoanglight.98@gmail.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Need some work? I'm your guy. # Add a description to your form

# NOTE
# Savana comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Keep</span> in touch # Add your title
  mailchimp__text: " 'Think different. Design with emotion. 🤞🏻' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: UA-3861857122 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-facebook", link: "https://www.facebook.com/RyNguyen20"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/c/rychanhome"}
- {icon: "ion-logo-dribbble", link: "https://dribbble.com/RyNguyen"}
- {icon: "ion-logo-codepen", link: "https://www.behance.net/rynguyen"}
# - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# - {icon: "ion-logo-codepen", link: "https://codepen.io"}
# - {icon: "ion-logo-vimeo", link: "https://vimeo.com"}

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed